### ISSUE TITLE
这个action是不是没执行

### ISSUE THREAD

**Issue by ohto-ai** [beiklive/GreenMe#1]
RT

**Comment by beiklive** [comment]
确实没执行，好像是在我手动提交一次后会触发一次

**Comment by beiklive** [comment]
![image](https://user-images.githubusercontent.com/73771431/199680564-c195fc14-67d5-4ad7-afff-2fadbe85fee6.png)
![image](https://user-images.githubusercontent.com/73771431/199680597-f39e883d-9faa-41fb-ae2b-100b3a2c73b4.png)

**Comment by ohto-ai** [comment]
> ![image](https://user-images.githubusercontent.com/73771431/199680564-c195fc14-67d5-4ad7-afff-2fadbe85fee6.png) ![image](https://user-images.githubusercontent.com/73771431/199680597-f39e883d-9faa-41fb-ae2b-100b3a2c73b4.png)

我想直接修改你的yaml，结果他自动fork了

**Comment by ohto-ai** [comment]
> 确实没执行，好像是在我手动提交一次后会触发一次

看逻辑是每天10:30触发的

**Comment by beiklive** [comment]
> 

但是没触发，不会是晚上十点吧
